version: '3.7'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - php
#    networks:
#      - app-network
#  certbot:
#    image: certbot/certbot


  mysqldb:
    image: mysql
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=testdata
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpass
#    networks:
#      - app-network

  php:
    image: php:7.2-fpm
    volumes:
      - ./nginx/www:/var/www
#    networks:
#      - app-network

#networks:
#  app-network:
#    driver: bridge
